# Generated by Django 5.2.8 on 2025-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consentimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
